
/**
 * Redux action types
 */

export const GET_CITIES_WEATHER_START = "GET_HOME_CITIES_WEATHER_START";
export const GET_CITIES_WEATHER_SUCCESS = "GET_HOME_CITIES_WEATHER_SUCCESS";
export const GET_CITIES_WEATHER_ERROR = "GET_HOME_CITIES_WEATHER_ERROR";
export const GET_WEATHER_START = "GET_WEATHER_START";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_ERROR = "GET_WEATHER_ERROR";
export const GET_DAILY_FORECAST_START = "GET_DAILY_FORECAST_START";
export const GET_DAILY_FORECAST_SUCCESS = "GET_DAILY_FORECAST_SUCCESS";
export const GET_DAILY_FORECAST_ERROR = "GET_DAILY_FORECAST_ERROR";